from .constants import CTGOV_DATASET_RAW_PATH
from .constants import CTGOV_DATASET_EXTENSIONS_PATH
from .constants import CTGOV_API_DOWNLOAD_BASE_URL
from .constants import CTGOV_NCTIDS_LIST_ALL_PATH
from .constants import CTGOV_DATASET_PATH
from .constants import CTGOV_PROTOCOL_PDF_LINKS_PATH
from .constants import CTGOV_EXTRACTED_PDFS_DATASET_PATH
from .main import download_registry_from_api